eval$s=%w'bins={"matsuyama"=>["BAhsKxV++PDzN5iZYQCADQMG4MeYHz8DjBkANoCZAWP/8fjnAw==",36],"matz"=>["BAhsKxp++ODzMwCDmWE2bBiADTMGbBh+jDH2MxgDjDE28H8DmGGGAWD/8eDzD2A=",48]};
bin,x=bins[ARGV[0]]||["BAhsKxZ++PAzgMHMDBsGYMOADcOPMT+GMcCYgf8bwMwAYPzH4x8w",39];
n=Marshal.load(bin.unpack("m")[0]);
y=7;
o="";
e=$s*3;
j=-1;
0.upto(x*y){|i|o<<((n[i]==1)?e[j+=1]:32);o<<((i%x==x-1)?10:"")};
puts(o);
#
'.join
